require('dotenv').config();
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const habilidadesData = [
  { nombre: 'Bola de Fuego' },
  { nombre: 'Escudo Arcano' },
  { nombre: 'Curacion' },
  { nombre: 'Rayo Helado' },
  { nombre: 'Golpe Critico' },
];

const cartasData = [
  { nombre: 'Mago Novato',     descripcion: 'Aprendiz de la academia',   rareza: 'COMUN',      imagen: 'mago_novato.png',     habilidadIdx: 0 },
  { nombre: 'Guerrero Joven',  descripcion: 'Esgrime una espada basica', rareza: 'COMUN',      imagen: 'guerrero_joven.png',  habilidadIdx: 4 },
  { nombre: 'Sacerdotisa',     descripcion: 'Sana a sus aliados',        rareza: 'RARA',       imagen: 'sacerdotisa.png',     habilidadIdx: 2 },
  { nombre: 'Caballero Real',  descripcion: 'Protector del reino',       rareza: 'RARA',       imagen: 'caballero_real.png',  habilidadIdx: 1 },
  { nombre: 'Hechicero',       descripcion: 'Domina las llamas',         rareza: 'EPICA',      imagen: 'hechicero.png',       habilidadIdx: 0 },
  { nombre: 'Asesino Silencioso', descripcion: 'Ataca por la espalda',   rareza: 'EPICA',      imagen: 'asesino.png',         habilidadIdx: 4 },
  { nombre: 'Dragon de Hielo', descripcion: 'Bestia ancestral',          rareza: 'LEGENDARIA', imagen: 'dragon_hielo.png',    habilidadIdx: 3 },
  { nombre: 'Fenix Eterno',    descripcion: 'Renace de las cenizas',     rareza: 'LEGENDARIA', imagen: 'fenix.png',           habilidadIdx: 0 },
];

// Pasos: contenidoTextual usa markdown (parseado en el front).
// Soporta: # headings, listas, **bold**, *italic*, `inline code`, [link](url),
//          > [!tip]/[!warning]/[!info] blockquotes,
//          ```python fenced code blocks (runnable inline con Pyodide).
//          ```python {expected="..."} para mini-retos validados.

const modulosData = [
  {
    titulo: 'Introduccion a Variables en Python',
    descripcion: 'Aprende a declarar y usar variables en Python.',
    orden: 1,
    pasos: [
      {
        orden: 1,
        titulo: 'Que es una variable?',
        contenidoTextual: [
          'Una **variable** es un nombre que apunta a un valor en memoria. Las usamos para guardar datos y reutilizarlos.',
          '',
          'En Python no se declara el tipo: el lenguaje lo infiere a partir del valor.',
          '',
          '```python',
          'edad = 17',
          'nombre = "Aria"',
          'print(nombre, "tiene", edad, "años")',
          '```',
          '',
          'Modifica los valores arriba y vuelve a probar para ver como cambia la salida.',
          '',
          '> [!tip]',
          '> Los nombres de variables deben empezar con letra o `_`, y no pueden ser palabras reservadas (`if`, `for`, `class`...).',
        ].join('\n'),
      },
      {
        orden: 2,
        titulo: 'Tipos basicos',
        contenidoTextual: [
          'Python tiene cuatro tipos basicos que vas a usar todo el tiempo:',
          '',
          '- `int` — numeros enteros: `1`, `42`, `-7`',
          '- `float` — numeros con decimales: `3.14`, `0.5`',
          '- `str` — texto entre comillas: `"hola"`, `\'mundo\'`',
          '- `bool` — valores logicos: `True` o `False`',
          '',
          'Puedes ver el tipo de algo con `type()`:',
          '',
          '```python',
          'print(type(42))',
          'print(type(3.14))',
          'print(type("hola"))',
          'print(type(True))',
          '```',
          '',
          '> [!info]',
          '> Las cadenas pueden usar comillas simples o dobles indistintamente. Elige una y se consistente.',
        ].join('\n'),
      },
      {
        orden: 3,
        titulo: 'Reto: declara y muestra',
        contenidoTextual: [
          'Tu turno. Crea las variables necesarias para que el programa imprima exactamente:',
          '',
          '```text',
          'Python tiene 4 tipos basicos',
          '```',
          '',
          'Usa una variable `lenguaje` con el valor `"Python"` y una variable `total` con el valor `4`.',
          '',
          '```python {expected="Python tiene 4 tipos basicos"}',
          '# Define lenguaje y total aqui',
          '# lenguaje = ...',
          '# total = ...',
          '',
          'print(lenguaje, "tiene", total, "tipos basicos")',
          '```',
          '',
          '> [!tip]',
          '> Pulsa **Probar** para ejecutar tu codigo. Cuando el output coincida vas a ver un badge `✓ Reto completado`.',
        ].join('\n'),
      },
    ],
  },
  {
    titulo: 'Introduccion a Bucles en Python',
    descripcion: 'Domina los bucles for y while para repetir tareas.',
    orden: 2,
    pasos: [
      {
        orden: 1,
        titulo: 'Que es un bucle?',
        contenidoTextual: [
          'Un **bucle** es una estructura que **repite** un bloque de codigo varias veces. Sin bucles tendrias que copiar y pegar el mismo `print` 100 veces para imprimir del 1 al 100.',
          '',
          'En Python hay dos bucles principales:',
          '',
          '1. `for` — recorre una secuencia (lista, rango, string...)',
          '2. `while` — repite mientras una condicion sea verdadera',
          '',
          'Veremos cada uno en los siguientes pasos.',
        ].join('\n'),
      },
      {
        orden: 2,
        titulo: 'Bucle for',
        contenidoTextual: [
          'El bucle `for` se combina con `range(n)` para repetir algo `n` veces:',
          '',
          '```python',
          'for i in range(5):',
          '    print("vuelta", i)',
          '```',
          '',
          'Tambien puedes recorrer una lista de elementos:',
          '',
          '```python',
          'frutas = ["manzana", "platano", "uva"]',
          'for fruta in frutas:',
          '    print(fruta.upper())',
          '```',
          '',
          '> [!tip]',
          '> `range(a, b)` recorre desde `a` hasta `b - 1`. Ojo: el segundo numero **no se incluye**.',
        ].join('\n'),
      },
      {
        orden: 3,
        titulo: 'Bucle while',
        contenidoTextual: [
          'El bucle `while` se ejecuta **mientras una condicion sea verdadera**. Es util cuando no sabes de antemano cuantas iteraciones necesitas.',
          '',
          '```python',
          'n = 1',
          'while n <= 5:',
          '    print(n)',
          '    n = n + 1',
          '```',
          '',
          '> [!warning]',
          '> Cuidado con los **bucles infinitos**: si la condicion nunca se vuelve falsa, el programa nunca termina. Asegurate de que algo dentro del `while` cambie la condicion.',
        ].join('\n'),
      },
      {
        orden: 4,
        titulo: 'Reto: suma 1 a 10',
        contenidoTextual: [
          'Usa un bucle para sumar los numeros del 1 al 10 e imprime el resultado.',
          '',
          'La salida esperada es:',
          '',
          '```text',
          '55',
          '```',
          '',
          '```python {expected="55"}',
          'total = 0',
          '# Tu codigo aqui',
          '',
          'print(total)',
          '```',
          '',
          '> [!tip]',
          '> Recuerda: `range(1, 11)` genera los numeros del 1 al 10 (el 11 no se incluye).',
        ].join('\n'),
      },
    ],
  },
  {
    titulo: 'Funciones en Python',
    descripcion: 'Aprende a definir y reutilizar funciones.',
    orden: 3,
    pasos: [
      {
        orden: 1,
        titulo: 'Definir una funcion',
        contenidoTextual: [
          'Una **funcion** es un bloque de codigo con nombre que puedes reutilizar.',
          '',
          'Se define con la palabra clave `def`:',
          '',
          '```python',
          'def saludar():',
          '    print("Hola, magos del codigo!")',
          '',
          '# Llamarla:',
          'saludar()',
          'saludar()',
          '```',
          '',
          'Las funciones evitan repetir codigo: cambias la logica en un lugar y se actualiza en todas las llamadas.',
          '',
          '> [!info]',
          '> El bloque de la funcion debe estar **indentado** (4 espacios). Si no, Python te dara un `IndentationError`.',
        ].join('\n'),
      },
      {
        orden: 2,
        titulo: 'Argumentos y return',
        contenidoTextual: [
          'Las funciones pueden recibir **argumentos** (datos de entrada) y devolver un valor con `return`:',
          '',
          '```python',
          'def cuadrado(n):',
          '    return n * n',
          '',
          'print(cuadrado(4))',
          'print(cuadrado(7))',
          '```',
          '',
          'Pueden recibir varios argumentos:',
          '',
          '```python',
          'def saludar(nombre, edad):',
          '    return f"Hola {nombre}, tienes {edad} años"',
          '',
          'print(saludar("Aria", 17))',
          '```',
          '',
          '> [!tip]',
          '> Sin `return`, una funcion devuelve `None` por defecto.',
        ].join('\n'),
      },
      {
        orden: 3,
        titulo: 'Reto: funcion es_par',
        contenidoTextual: [
          'Implementa la funcion `es_par(n)` que **devuelve** `True` si `n` es par y `False` si es impar.',
          '',
          'Output esperado:',
          '',
          '```text',
          'True',
          'False',
          'True',
          '```',
          '',
          '```python {expected="True\\nFalse\\nTrue"}',
          'def es_par(n):',
          '    # Completa la funcion',
          '    pass',
          '',
          'print(es_par(4))',
          'print(es_par(7))',
          'print(es_par(0))',
          '```',
          '',
          '> [!tip]',
          '> El operador modulo `%` devuelve el resto de una division. `n % 2 == 0` es verdadero cuando `n` es par.',
        ].join('\n'),
      },
    ],
  },
];

// Cada descripcion usa el mismo formato markdown que los pasos (parseado en
// el front). Convencion para ser amigable con el alumno:
// 1. Intro corta del problema
// 2. Ejemplo concreto de entrada/salida
// 3. Lista de "Lo que necesitas saber"
// 4. `> [!tip]` con una pista accesible
// 5. ::: spoiler "💡 Pista mas fuerte" — segundo nivel de ayuda
// 6. ::: spoiler "✅ Ver solucion" — escapar si esta atascado
//
// Nota: el runner del front parchea input() para que el prompt NO contamine
// stdout. Por eso `input("Numero: ")` funciona igual que `input()` aqui.

const ejerciciosData = [
  {
    titulo: 'Suma de dos numeros',
    descripcion: [
      'Lee **dos numeros enteros**, cada uno en su propia linea, y muestra su **suma**.',
      '',
      '## Ejemplo',
      '',
      '```text',
      'Entrada:',
      '2',
      '3',
      'Salida: 5',
      '```',
      '',
      '## Lo que necesitas saber',
      '',
      '- `input()` lee una linea de la entrada.',
      '- `int(x)` convierte un string a entero.',
      '- `print(x)` imprime el resultado.',
      '',
      '> [!tip]',
      '> Cuidado con los tipos: lo que devuelve `input()` es **texto**, no numero. Tienes que convertirlo con `int()` antes de sumar.',
      '',
      '::: spoiler "💡 Pista mas fuerte"',
      'Llama a `input()` dos veces, una para cada numero:',
      '',
      '```python {runnable=false}',
      'a = int(input())',
      'b = int(input())',
      '```',
      '',
      'Ahora suma e imprime.',
      ':::',
      '',
      '::: spoiler "✅ Ver solucion"',
      'Solucion directa:',
      '',
      '```python {runnable=false}',
      'a = int(input())',
      'b = int(input())',
      'print(a + b)',
      '```',
      '',
      'Tambien funciona en una linea:',
      '',
      '```python {runnable=false}',
      'print(int(input()) + int(input()))',
      '```',
      ':::',
    ].join('\n'),
    dificultad: 'FACIL',
    lenguaje: 'python',
    tiempoEstimadoSeg: 300,
    moduloIdx: 0,
    casosPrueba: [
      { input: '2\n3', outputEsperado: '5' },
      { input: '10\n20', outputEsperado: '30' },
      { input: '-5\n5', outputEsperado: '0' },
    ],
    solucionesCodigo: [
      'a = int(input())\nb = int(input())\nprint(a + b)',
      'print(int(input()) + int(input()))',
      'a, b = int(input()), int(input())\nprint(a + b)',
      'x = int(input())\ny = int(input())\nprint(x + y)',
    ],
    recompensas: [
      { tipo: 'PUNTOS', probabilidad: '1.00', cantidad: 10 },
      { tipo: 'CARTA',  probabilidad: '1.00', cantidad: 1 },
    ],
  },
  {
    titulo: 'Imprimir del 1 al N',
    descripcion: [
      'Lee un numero **N** y muestra los numeros del 1 al N **separados por espacios** en una sola linea.',
      '',
      '## Ejemplo',
      '',
      '```text',
      'Entrada: 5',
      'Salida:  1 2 3 4 5',
      '```',
      '',
      '## Lo que necesitas saber',
      '',
      '- `range(1, n+1)` genera los numeros del 1 al N (recuerda: el segundo numero no se incluye).',
      '- Un bucle `for` recorre cada numero.',
      '- `print(x, end=" ")` imprime sin saltar de linea (con un espacio al final).',
      '- O usa `print(*lista)` para imprimir todos los elementos separados por espacios.',
      '',
      '> [!tip]',
      '> Si pones cada `print()` en su propia linea, cada numero va a aparecer en una linea distinta. **Eso no es lo que pide el ejercicio.** Tienes que imprimirlos todos en la misma linea.',
      '',
      '::: spoiler "💡 Pista mas fuerte"',
      'Hay dos formas faciles:',
      '',
      '1. Con `end=" "` dentro del print:',
      '',
      '```python {runnable=false}',
      'for i in range(1, n+1):',
      '    print(i, end=" ")',
      '```',
      '',
      '2. Con el operador `*` que "desempaqueta" el rango:',
      '',
      '```python {runnable=false}',
      'print(*range(1, n+1))',
      '```',
      ':::',
      '',
      '::: spoiler "✅ Ver solucion"',
      '```python {runnable=false}',
      'n = int(input())',
      'print(*range(1, n+1))',
      '```',
      '',
      'O con join:',
      '',
      '```python {runnable=false}',
      'n = int(input())',
      'print(" ".join(str(i) for i in range(1, n+1)))',
      '```',
      ':::',
    ].join('\n'),
    dificultad: 'FACIL',
    lenguaje: 'python',
    tiempoEstimadoSeg: 400,
    moduloIdx: 1,
    casosPrueba: [
      { input: '5', outputEsperado: '1 2 3 4 5' },
      { input: '1', outputEsperado: '1' },
      { input: '3', outputEsperado: '1 2 3' },
    ],
    solucionesCodigo: [
      'n = int(input())\nprint(*range(1, n+1))',
      'n = int(input())\nprint(" ".join(str(i) for i in range(1, n+1)))',
    ],
    recompensas: [
      { tipo: 'PUNTOS', probabilidad: '1.00', cantidad: 10 },
      { tipo: 'CARTA',  probabilidad: '1.00', cantidad: 1 },
    ],
  },
  {
    titulo: 'Factorial',
    descripcion: [
      'Lee un numero **N** y muestra su factorial.',
      '',
      'El factorial de N (escrito **N!**) es el producto de todos los enteros del 1 hasta N:',
      '',
      '- `5! = 5 × 4 × 3 × 2 × 1 = 120`',
      '- `3! = 3 × 2 × 1 = 6`',
      '- `0! = 1` (por definicion)',
      '',
      '## Ejemplo',
      '',
      '```text',
      'Entrada: 5',
      'Salida:  120',
      '```',
      '',
      '## Lo que necesitas saber',
      '',
      '- Necesitas **multiplicar** varios numeros, no sumar.',
      '- Empieza con un acumulador en **1** (no en 0, porque cualquier cosa por 0 es 0).',
      '- Recorre del 1 al N con un `for` y multiplica.',
      '',
      '> [!tip]',
      '> Si vas a usar un acumulador, **dale un valor inicial antes del bucle**. Para sumas se usa `0`, para productos se usa `1`.',
      '',
      '> [!warning]',
      '> Caso especial: `0!` es `1`. Tu codigo deberia funcionar correctamente sin ningun `if` especial si empiezas con `resultado = 1` y `range(1, n+1)` queda vacio cuando `n = 0`.',
      '',
      '::: spoiler "💡 Pista mas fuerte"',
      'Esqueleto del codigo:',
      '',
      '```python {runnable=false}',
      'n = int(input())',
      'resultado = 1',
      'for i in range(1, n+1):',
      '    # multiplica resultado por i',
      '    ...',
      'print(resultado)',
      '```',
      '',
      'Pista: para multiplicar y guardar el resultado, escribes `resultado = resultado * i` o el atajo `resultado *= i`.',
      ':::',
      '',
      '::: spoiler "✅ Ver solucion (iterativa)"',
      '```python {runnable=false}',
      'n = int(input())',
      'resultado = 1',
      'for i in range(1, n+1):',
      '    resultado *= i',
      'print(resultado)',
      '```',
      ':::',
      '',
      '::: spoiler "✨ Bonus: version recursiva"',
      'Para los curiosos — usando recursion:',
      '',
      '```python {runnable=false}',
      'def factorial(n):',
      '    if n <= 1:',
      '        return 1',
      '    return n * factorial(n - 1)',
      '',
      'print(factorial(int(input())))',
      '```',
      '',
      'Ambas son validas. La iterativa es mas eficiente.',
      ':::',
    ].join('\n'),
    dificultad: 'MEDIO',
    lenguaje: 'python',
    tiempoEstimadoSeg: 600,
    moduloIdx: 2,
    casosPrueba: [
      { input: '5', outputEsperado: '120' },
      { input: '0', outputEsperado: '1' },
      { input: '7', outputEsperado: '5040' },
    ],
    solucionesCodigo: [
      'def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n-1)\nprint(factorial(int(input())))',
      'n = int(input())\nresult = 1\nfor i in range(1, n+1):\n    result *= i\nprint(result)',
    ],
    recompensas: [
      { tipo: 'PUNTOS', probabilidad: '1.00', cantidad: 20 },
      { tipo: 'CARTA',  probabilidad: '1.00', cantidad: 1 },
    ],
  },
  {
    titulo: 'Es par o impar',
    descripcion: [
      'Lee un **numero entero** y muestra:',
      '',
      '- `par` — si el numero es divisible entre 2',
      '- `impar` — si no lo es',
      '',
      '## Ejemplo',
      '',
      '```text',
      'Entrada: 4',
      'Salida:  par',
      '',
      'Entrada: 7',
      'Salida:  impar',
      '```',
      '',
      '## Lo que necesitas saber',
      '',
      '- Operador modulo `%`: devuelve el **resto** de una division. Por ejemplo:',
      '  - `10 % 3 = 1` (10 dividido 3 da 3, sobra 1)',
      '  - `4 % 2 = 0` (4 dividido 2 da 2, sobra 0)',
      '- Un numero es **par** cuando `n % 2 == 0`.',
      '- `if` / `else` para decidir que imprimir.',
      '',
      '> [!tip]',
      '> El resultado debe ser exactamente `par` o `impar` (en minusculas, sin comillas, sin punto). Cualquier texto adicional cuenta como incorrecto.',
      '',
      '> [!info]',
      '> Puedes usar `input("Numero: ")` con un prompt si quieres. El runner del entorno **ignora el prompt** automaticamente, asi que no contamina la salida.',
      '',
      '::: spoiler "💡 Pista mas fuerte"',
      'Estructura basica del programa:',
      '',
      '```python {runnable=false}',
      'n = int(input())',
      'if # condicion para par:',
      '    print("par")',
      'else:',
      '    print("impar")',
      '```',
      '',
      'La condicion es: el resto de dividir `n` entre 2 es cero.',
      ':::',
      '',
      '::: spoiler "✅ Ver solucion"',
      '```python {runnable=false}',
      'n = int(input())',
      'if n % 2 == 0:',
      '    print("par")',
      'else:',
      '    print("impar")',
      '```',
      '',
      'Variante en una linea con operador ternario:',
      '',
      '```python {runnable=false}',
      'n = int(input())',
      'print("par" if n % 2 == 0 else "impar")',
      '```',
      ':::',
    ].join('\n'),
    dificultad: 'FACIL',
    lenguaje: 'python',
    tiempoEstimadoSeg: 300,
    moduloIdx: 0,
    casosPrueba: [
      { input: '4', outputEsperado: 'par' },
      { input: '7', outputEsperado: 'impar' },
      { input: '0', outputEsperado: 'par' },
    ],
    solucionesCodigo: [
      'n = int(input())\nprint("par" if n % 2 == 0 else "impar")',
      'n = int(input())\nif n % 2 == 0:\n    print("par")\nelse:\n    print("impar")',
    ],
    recompensas: [
      { tipo: 'PUNTOS', probabilidad: '1.00', cantidad: 10 },
      { tipo: 'CARTA',  probabilidad: '1.00', cantidad: 1 },
    ],
  },
  {
    titulo: 'Suma de lista',
    descripcion: [
      'Lee una linea con **varios numeros separados por espacios** e imprime su suma.',
      '',
      '## Ejemplo',
      '',
      '```text',
      'Entrada: 1 2 3 4 5',
      'Salida:  15',
      '',
      'Entrada: 10',
      'Salida:  10',
      '```',
      '',
      '## Lo que necesitas saber',
      '',
      '- `input().split()` te da una lista de strings.',
      '- `map(int, lista)` aplica `int()` a cada elemento → te devuelve un iterable de enteros.',
      '- `sum(iterable)` suma todos los elementos.',
      '',
      '> [!tip]',
      '> No sabes cuantos numeros va a tener cada caso (puede ser uno solo o muchos). Tu codigo debe funcionar para **cualquier cantidad**.',
      '',
      '::: spoiler "💡 Pista mas fuerte"',
      'Tres pasos:',
      '',
      '1. Lee la linea: `linea = input()`',
      '2. Convierte a lista de enteros: usa `split()` y `map(int, ...)` o list comprehension.',
      '3. Imprime la suma con `sum(...)`.',
      ':::',
      '',
      '::: spoiler "✅ Ver solucion"',
      'Version corta:',
      '',
      '```python {runnable=false}',
      'print(sum(map(int, input().split())))',
      '```',
      '',
      'Version mas legible (paso a paso):',
      '',
      '```python {runnable=false}',
      'linea = input()',
      'partes = linea.split()',
      'numeros = [int(p) for p in partes]',
      'print(sum(numeros))',
      '```',
      ':::',
    ].join('\n'),
    dificultad: 'MEDIO',
    lenguaje: 'python',
    tiempoEstimadoSeg: 500,
    moduloIdx: 1,
    casosPrueba: [
      { input: '1 2 3 4 5', outputEsperado: '15' },
      { input: '10', outputEsperado: '10' },
      { input: '-1 -2 -3', outputEsperado: '-6' },
    ],
    solucionesCodigo: [
      'print(sum(map(int, input().split())))',
      'nums = [int(x) for x in input().split()]\nprint(sum(nums))',
    ],
    recompensas: [
      { tipo: 'PUNTOS', probabilidad: '1.00', cantidad: 15 },
      { tipo: 'CARTA',  probabilidad: '1.00', cantidad: 1 },
    ],
  },
];

async function main() {
  console.log('[seed] Limpiando datos previos...');
  // Order matters due to FKs
  await prisma.usuarioPaso.deleteMany();
  await prisma.usuarioCarta.deleteMany();
  await prisma.ejercicioResuelto.deleteMany();
  await prisma.ejercicioActivo.deleteMany();
  await prisma.recompensa.deleteMany();
  await prisma.ejercicio.deleteMany();
  await prisma.paso.deleteMany();
  await prisma.modulo.deleteMany();
  await prisma.cartaNivel.deleteMany();
  await prisma.carta.deleteMany();
  await prisma.habilidad.deleteMany();

  console.log('[seed] Habilidades...');
  const habilidades = [];
  for (const h of habilidadesData) {
    habilidades.push(await prisma.habilidad.create({ data: h }));
  }

  console.log('[seed] Cartas + niveles...');
  for (const c of cartasData) {
    const carta = await prisma.carta.create({
      data: {
        nombre: c.nombre,
        descripcion: c.descripcion,
        rareza: c.rareza,
        imagen: c.imagen,
        habilidadId: habilidades[c.habilidadIdx].id,
        niveles: {
          create: [
            { nivel: 1, dano: 10, salud: 50, mana: 20, danoHabilidad: 15 },
            { nivel: 2, dano: 15, salud: 70, mana: 30, danoHabilidad: 22 },
            { nivel: 3, dano: 22, salud: 100, mana: 45, danoHabilidad: 33 },
          ],
        },
      },
    });
    console.log(`  - carta: ${carta.nombre} (${c.rareza})`);
  }

  console.log('[seed] Modulos + pasos...');
  const modulos = [];
  for (const m of modulosData) {
    const modulo = await prisma.modulo.create({
      data: {
        titulo: m.titulo,
        descripcion: m.descripcion,
        orden: m.orden,
        pasos: {
          create: m.pasos.map((p) => ({
            titulo: p.titulo,
            contenidoTextual: p.contenidoTextual,
            orden: p.orden,
          })),
        },
      },
    });
    modulos.push(modulo);
    console.log(`  - modulo: ${modulo.titulo}`);
  }

  console.log('[seed] Ejercicios + recompensas...');
  for (const e of ejerciciosData) {
    const ejercicio = await prisma.ejercicio.create({
      data: {
        titulo: e.titulo,
        descripcion: e.descripcion,
        dificultad: e.dificultad,
        lenguaje: e.lenguaje,
        tiempoEstimadoSeg: e.tiempoEstimadoSeg,
        moduloId: modulos[e.moduloIdx]?.id ?? null,
        casosPrueba: e.casosPrueba,
        solucionesCodigo: e.solucionesCodigo,
        recompensas: {
          create: e.recompensas.map((r) => ({
            tipo: r.tipo,
            probabilidad: r.probabilidad,
            cantidad: r.cantidad,
          })),
        },
      },
    });
    console.log(`  - ejercicio: ${ejercicio.titulo} (${e.dificultad})`);
  }

  console.log('[seed] OK');
}

main()
  .catch((err) => {
    console.error('[seed] ERROR:', err);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
